---
apiVersion: user.openshift.io/v1
fullName: Bob Marley
kind: User
metadata:
  name: bmarley
---
apiVersion: user.openshift.io/v1
fullName: Janice Joplin
kind: User
metadata:
  name: jjoplin
---
apiVersion: user.openshift.io/v1
fullName: Ozzy Osbourne
kind: User
metadata:
  name: oosbourne