{{- if .Values.operators }}
{{- range $app := .Values.operators }}
{{- $namespace := $app.namespace.name }}
{{- if $app.enabled }}
{{- if $app.namespace.create }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
