{{- if .Values.operators }}
{{- range $app := .Values.operators }}
{{- $name := $app.name }}
{{- $namespace := $app.namespace.name }}
{{- if $app.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $name }}-operator-installer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ $name }}-operator-installer
  namespace: {{ $namespace }}
{{- end }}
{{- end }}
{{- end }}
