{{- if .Values.operators }}
{{- range $app := .Values.operators }}
{{- $name := $app.name }}
{{- $namespace := $app.namespace.name }}
{{- if $app.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}-operator-installer
  namespace: {{ $namespace }}
{{- end }}
{{- end }}
{{- end }}